
export const Users = [
    {
      id:1,
      profilePicture: "/assets/person/1.jpg",
      username: "Aayush Panthi",
    },
    {
      id:2,
      profilePicture: "/assets/person/2.jpg",
      username: "Bibek Rokaya",
    },
    {
      id:3,
      profilePicture: "/assets/person/3.jpg",
      username: "Aagya Koirala",
    },
    {
      id:4,
      profilePicture: "/assets/person/4.jpg",
      username: "Nabin Gotami",
    },
    {
      id:5,
      profilePicture: "/assets/person/5.jpg",
      username: "Pratik Devkota",
    },
    {
      id:6,
      profilePicture: "/assets/person/6.jpg",
      username: "Basanta Regmi",
    },
    {
      id:7,
      profilePicture: "/assets/person/7.jpg",
      username: "Sundar Oli",
    },
    {
      id:8,
      profilePicture: "/assets/person/8.jpg",
      username: "Arun Koirala",
    },
    {
      id:9,
      profilePicture: "/assets/person/9.jpg",
      username: "Hemraj Budha",
    },
    {
      id:10,
      profilePicture: "/assets/person/10.jpg",
      username: "Bhisma Pratigya kc",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "/assets/post/1.jpeg", 
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "/assets/post/2.jpeg",
      desc: "No stress.",
      date: "15 mins ago",
      userId: 2,
      like: 200,
      comment: 5,
    },
    {
      id: 3,
      desc: "yes i did it.",
      photo: "/assets/post/3.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 20,
    },
    {
      id: 4,
      desc : "I am healthier than you.",
      photo: "/assets/post/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 70,
      comment: 30,
    },
    {
      id: 5,
      desc : "Friends at work",
      photo: "../../assets/post/5.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 230,
      comment: 50,
    },
    {
      id: 6,
      desc : "Who said i Can't see John Cena.",
      photo: "/assets/post/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 16,
    },
    {
      id: 7,
      desc: "Kids are Happy.",
      photo: "../../assets/post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 13,
    },
    {
      id: 8,
      desc : "I don't know where I am. ",
      photo: "/assets/post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 150,
      comment: 11,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "/assets/post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 110,
      comment: 20,
    },
    {
      id: 10,
      desc : "learner",
      photo: "/assets/post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];